message_new:
    path:    contacto
    methods:  [GET, POST]
    defaults: { _controller: AppBundle:Message:new }
  
message_show:
    path:     /contacto/{id}
    methods:  [GET]
    defaults: { _controller: AppBundle:Message:show }