services_index:
    path:     /servicios
    methods:  [GET]
    defaults: { _controller: AppBundle:Service:index }

service_new:
    path:    /new/service
    methods:  [GET, POST]
    defaults: { _controller: AppBundle:Service:new }

service_show:
    path:     /servicio/{slug}
    methods:  [GET]
    defaults: { _controller: AppBundle:Service:show }

service_edit:
    path:     /edit/service/{id}
    methods:  [GET, POST]
    defaults: { _controller: AppBundle:Service:edit }
 
service_delete:
    path:     /service/{id}
    methods:  [DELETE]
    defaults: { _controller: AppBundle:Service:delete }