services:
    app.admin.information:
        class: AppBundle\Admin\InformationAdmin
        arguments: [~, AppBundle\Entity\Information, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Informaci贸n", label: "Informaci贸n", icon: "<i class=\"fa fa-info-circle\"></i>" }
        public: true

    app.admin.service:
        class: AppBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Servicios", label: "Servicios", icon: "<i class=\"fa fa-bookmark\"></i>" }
        arguments:
            - ~
            - AppBundle\Entity\Service
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true

    app.admin.service_detail:
        class: AppBundle\Admin\ServiceDetailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Servicios", label: "Detalles de Servicios", icon: "<i class=\"fa fa-bookmark\"></i>" }
        arguments:
            - ~
            - AppBundle\Entity\ServiceDetail
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true

    app.admin.client:
        class: AppBundle\Admin\ClientAdmin
        arguments: [~, AppBundle\Entity\Client, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Clientes", label: "Clientes", icon: "<i class=\"fa fa-address-book\"></i>" }
        public: true
    
    app.admin.message:
        class: AppBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mensajes", label: "Mensajes", icon: "<i class=\"fa fa-envelope\"></i>" }
        arguments:
            - ~
            - AppBundle\Entity\Message
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true

    app.admin.training:
        class: AppBundle\Admin\TrainingAdmin
        arguments: [~, AppBundle\Entity\Training, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Capacitaciones, label: "Capacitaci贸n", icon: "<i class=\"fa fa-calendar\"></i>" }
        public: true

    app.admin.training_cost:
        class: AppBundle\Admin\TrainingCostAdmin
        arguments: [~, AppBundle\Entity\TrainingCost, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Capacitaciones, label: "Costo de Capacitaci贸n", icon: "<i class=\"fa fa-calendar\"></i>" }
        public: true
