services:
    app.admin.service:
        class: AppBundle\Admin\ServiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Servicios", label: "Servicios", icon: "<i class=\"fa fa-bookmark\"></i>" }
        arguments:
            - ~
            - AppBundle\Entity\Service
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true

    app.admin.service_detail:
        class: AppBundle\Admin\ServiceDetailAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Servicios", label: "Detalles de Servicios", icon: "<i class=\"fa fa-bookmark\"></i>" }
        arguments:
            - ~
            - AppBundle\Entity\ServiceDetail
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true
    
    app.admin.message:
        class: AppBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mensajes", label: "Mensajes", icon: "<i class=\"fa fa-envelope\"></i>" }
        arguments:
            - ~
            - AppBundle\Entity\Message
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
        public: true

    app.admin.information:
        class: AppBundle\Admin\InformationAdmin
        arguments: [~, AppBundle\Entity\Information, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Información", label: "Información", icon: "<i class=\"fa fa-info\"></i>" }
        public: true
