app_index:
    path:     /
    defaults: { _controller: AppBundle:Index:index }

#Servicios
app_service: 
    resource: "@AppBundle/Resources/config/routing/service.yml"

#Contacto
app_contact: 
    resource: "@AppBundle/Resources/config/routing/message.yml"